# Employment insurance claims received by province and territory, monthly, seasonally adjusted

Retrieved from https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=1410000501

In [1]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv('./EI_claims.csv', on_bad_lines='skip')
df

,REF_DATE,GEO,DGUID,Type of claim,Claim detail,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2018-06,Canada,2016A000011124,"Initial and renewal claims, seasonally adjusted",Received,Claims,68,units,0,v1992295,1.4.1,238940.0,NaN,NaN,NaN,0
1,2018-07,Canada,2016A000011124,"Initial and renewal claims, seasonally adjusted",Received,Claims,68,units,0,v1992295,1.4.1,234300.0,NaN,NaN,NaN,0
2,2018-08,Canada,2016A000011124,"Initial and renewal claims, seasonally adjusted",Received,Claims,68,units,0,v1992295,1.4.1,236670.0,NaN,NaN,NaN,0
3,2018-09,Canada,2016A000011124,"Initial and renewal claims, seasonally adjusted",Received,Claims,68,units,0,v1992295,1.4.1,238020.0,NaN,NaN,NaN,0
4,2018-10,Canada,2016A000011124,"Initial and renewal claims, seasonally adjusted",Received,Claims,68,units,0,v1992295,1.4.1,223980.0,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2022-06,Ontario,2016A000235,"Initial and renewal claims, seasonally adjusted",Received,Claims,68,units,0,v1992301,7.4.1,75820.0,NaN,NaN,NaN,0
102,2022-07,Ontario,2016A000235,"Initial and renewal claims, seasonally adjusted",Received,Claims,68,units,0,v1992301,7.4.1,80010.0,NaN,NaN,NaN,0
103,2022-08,Ontario,2016A000235,"Initial and renewal claims, seasonally adjusted",Received,Claims,68,units,0,v1992301,7.4.1,80210.0,NaN,NaN,NaN,0
104,2022-09,Ontario,2016A000235,"Initial and renewal claims, seasonally adjusted",Received,Claims,68,units,0,v1992301,7.4.1,81770.0,NaN,NaN,NaN,0
105,2022-10,Ontario,2016A000235,"Initial and renewal claims, seasonally adjusted",Received,Claims,68,units,0,v1992301,7.4.1,79990.0,NaN,NaN,NaN,0

In [19]:
#Pull necessary columns
df_in = df[['REF_DATE', 'GEO', 'VALUE']]

#Filter to only Ontario
df_in = df_in.loc[df_in['GEO'] == 'Ontario']
df_in = df_in.drop(columns='GEO')
df_in

df_in = df_in.rename(columns={'REF_DATE':'ds', 'VALUE':'statcan_ei_claims'})
df_in

          ds  statcan_ei_claims
53   2018-06            72290.0
54   2018-07            72300.0
55   2018-08            74560.0
56   2018-09            73930.0
57   2018-10            69510.0
58   2018-11            72440.0
59   2018-12            70690.0
60   2019-01            72370.0
61   2019-02            74550.0
62   2019-03            76070.0
63   2019-04            72390.0
64   2019-05            72380.0
65   2019-06            72310.0
66   2019-07            79320.0
67   2019-08            73570.0
68   2019-09            78120.0
69   2019-10            75770.0
70   2019-11            77760.0
71   2019-12            79720.0
72   2020-01            78380.0
73   2020-02            76820.0
74   2020-03                NaN
75   2020-04                NaN
76   2020-05                NaN
77   2020-06                NaN
78   2020-07                NaN
79   2020-08                NaN
80   2020-09                NaN
81   2020-10           572560.0
82   2020-11           126390.0
83   2020-12           145690.0
84   2021-01           172540.0
85   2021-02           104930.0
86   2021-03            57910.0
87   2021-04           168590.0
88   2021-05           103800.0
89   2021-06            87530.0
90   2021-07            55290.0
91   2021-08            81380.0
92   2021-09           101030.0
93   2021-10           106560.0
94   2021-11            84560.0
95   2021-12           104310.0
96   2022-01           128410.0
97   2022-02            83850.0
98   2022-03            78180.0
99   2022-04            77000.0
100  2022-05            76210.0
101  2022-06            75820.0
102  2022-07            80010.0
103  2022-08            80210.0
104  2022-09            81770.0
105  2022-10            79990.0

In [20]:
df = pd.read_csv('./cpi.csv', on_bad_lines='skip')
df

,REF_DATE,GEO,DGUID,Products and product groups,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2018-01,Ontario,2016A000235,All-items,2002=100,17,units,0,v41691919,14.200,133.2,NaN,NaN,NaN,1
1,2018-02,Ontario,2016A000235,All-items,2002=100,17,units,0,v41691919,14.200,134.0,NaN,NaN,NaN,1
2,2018-03,Ontario,2016A000235,All-items,2002=100,17,units,0,v41691919,14.200,134.6,NaN,NaN,NaN,1
3,2018-04,Ontario,2016A000235,All-items,2002=100,17,units,0,v41691919,14.200,134.8,NaN,NaN,NaN,1
4,2018-05,Ontario,2016A000235,All-items,2002=100,17,units,0,v41691919,14.200,134.9,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,2022-07,Ontario,2016A000235,Services,2002=100,17,units,0,v41692043,14.282,167.8,NaN,NaN,NaN,1
881,2022-08,Ontario,2016A000235,Services,2002=100,17,units,0,v41692043,14.282,167.7,NaN,NaN,NaN,1
882,2022-09,Ontario,2016A000235,Services,2002=100,17,units,0,v41692043,14.282,168.3,NaN,NaN,NaN,1
883,2022-10,Ontario,2016A000235,Services,2002=100,17,units,0,v41692043,14.282,168.9,NaN,NaN,NaN,1
884,2022-11,Ontario,2016A000235,Services,2002=100,17,units,0,v41692043,14.282,169.1,NaN,NaN,NaN,1

In [33]:
#Define components to look at 
categories= ['All-items', 'Food', 'Shelter']

#Filter to only Ontario
df_in = df.loc[df['Products and product groups'].isin(categories)]
df_in = df_in[['REF_DATE', 'Products and product groups', 'VALUE']]

#Convert each category to individual columns 
df_in = df_in.pivot_table(values='VALUE', columns='Products and product groups', index= df_in.REF_DATE)
df_in = df_in.reset_index()

df_in = df_in.rename(columns={'REF_DATE':'ds', 
                              'All-items':'cpi-allitems',
                              'Food':'cpi-food',
                              'Shelter':'cpi-shelter'
                             })

#Convert to datetime
df_in['ds'] = pd.to_datetime(df_in['ds'])
df_in = df_in.set_index('ds')
df_in

Products and product groups  cpi-allitems  cpi-food  cpi-shelter
ds
2018-01-01                          133.2     146.3        141.7
2018-02-01                          134.0     146.6        141.9
2018-03-01                          134.6     146.0        141.9
2018-04-01                          134.8     147.0        141.9
2018-05-01                          134.9     146.7        142.1
2018-06-01                          135.3     148.3        142.4
2018-07-01                          136.0     148.9        142.6
2018-08-01                          135.9     148.1        142.9
2018-09-01                          135.2     146.7        143.2
2018-10-01                          135.6     146.3        143.7
2018-11-01                          135.1     148.0        143.9
2018-12-01                          135.0     150.2        144.1
2019-01-01                          135.2     151.6        145.0
2019-02-01                          136.0     151.9        145.5
2019-03-01                          137.0     151.9        145.8
2019-04-01                          137.4     151.8        146.5
2019-05-01                          138.1     152.7        146.6
2019-06-01                          138.0     153.7        146.8
2019-07-01                          138.8     153.8        147.3
2019-08-01                          138.5     153.3        147.4
2019-09-01                          137.5     151.9        147.3
2019-10-01                          137.9     151.4        148.3
2019-11-01                          137.7     152.6        148.6
2019-12-01                          137.8     154.2        148.9
2020-01-01                          138.0     155.3        149.0
2020-02-01                          138.7     154.4        149.3
2020-03-01                          137.9     154.5        149.3
2020-04-01                          137.3     156.4        148.4
2020-05-01                          137.5     156.1        148.0
2020-06-01                          138.6     156.6        149.7
2020-07-01                          138.8     157.0        149.5
2020-08-01                          138.6     155.9        150.2
2020-09-01                          138.3     154.6        150.5
2020-10-01                          138.9     155.0        152.2
2020-11-01                          139.0     155.3        152.4
2020-12-01                          138.8     155.2        152.3
2021-01-01                          139.5     157.1        151.1
2021-02-01                          140.2     157.1        151.9
2021-03-01                          141.0     157.6        153.5
2021-04-01                          141.8     157.2        154.6
2021-05-01                          142.6     158.1        155.7
2021-06-01                          143.1     158.1        156.9
2021-07-01                          143.7     159.2        157.2
2021-08-01                          144.1     160.0        157.4
2021-09-01                          144.4     160.3        158.4
2021-10-01                          145.7     160.6        159.8
2021-11-01                          146.0     162.8        160.5
2021-12-01                          146.0     164.1        161.5
2022-01-01                          147.4     166.7        161.8
2022-02-01                          148.8     168.8        162.8
2022-03-01                          150.8     170.5        164.8
2022-04-01                          151.6     171.6        166.4
2022-05-01                          153.7     173.4        167.2
2022-06-01                          154.4     173.2        167.4
2022-07-01                          154.6     174.6        168.8
2022-08-01                          154.1     175.9        168.6
2022-09-01                          154.1     176.9        169.4
2022-10-01                          155.2     176.4        170.7
2022-11-01                          155.4     178.8        171.6

In [25]:
df.loc[df['Products and product groups'].isin(['All-items', 'Food', 'Shelter'])]

,REF_DATE,GEO,DGUID,Products and product groups,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2018-01,Ontario,2016A000235,All-items,2002=100,17,units,0,v41691919,14.20,133.2,NaN,NaN,NaN,1
1,2018-02,Ontario,2016A000235,All-items,2002=100,17,units,0,v41691919,14.20,134.0,NaN,NaN,NaN,1
2,2018-03,Ontario,2016A000235,All-items,2002=100,17,units,0,v41691919,14.20,134.6,NaN,NaN,NaN,1
3,2018-04,Ontario,2016A000235,All-items,2002=100,17,units,0,v41691919,14.20,134.8,NaN,NaN,NaN,1
4,2018-05,Ontario,2016A000235,All-items,2002=100,17,units,0,v41691919,14.20,134.9,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,2022-07,Ontario,2016A000235,Shelter,2002=100,17,units,0,v41691952,14.79,168.8,NaN,NaN,NaN,1
173,2022-08,Ontario,2016A000235,Shelter,2002=100,17,units,0,v41691952,14.79,168.6,NaN,NaN,NaN,1
174,2022-09,Ontario,2016A000235,Shelter,2002=100,17,units,0,v41691952,14.79,169.4,NaN,NaN,NaN,1
175,2022-10,Ontario,2016A000235,Shelter,2002=100,17,units,0,v41691952,14.79,170.7,NaN,NaN,NaN,1
176,2022-11,Ontario,2016A000235,Shelter,2002=100,17,units,0,v41691952,14.79,171.6,NaN,NaN,NaN,1